### ISSUE TITLE
不支持上传图片么？

### ISSUE THREAD

**Issue by charlescui** [aliyun/aliyun-oss-ruby-sdk#1]
我通过put_object上传jpeg的图片，SDK报错如下：

```
#<Encoding::CompatibilityError: inspected result must be ASCII only or use the default external encoding>
```

backtrace如下：

```
/home/www/.rvm/gems/ruby-2.2.1/gems/aliyun-sdk-0.1.6/lib/aliyun/oss/http.rb:228:in `inspect'
/home/www/.rvm/gems/ruby-2.2.1/gems/aliyun-sdk-0.1.6/lib/aliyun/oss/http.rb:228:in `inspect'/home/www/.rvm/gems/ruby-2.2.1/gems/aliyun-sdk-0.1.6/lib/aliyun/oss/http.rb:228:in `do_request'
/home/www/.rvm/gems/ruby-2.2.1/gems/aliyun-sdk-0.1.6/lib/aliyun/oss/http.rb:168:in `put'
/home/www/.rvm/gems/ruby-2.2.1/gems/aliyun-sdk-0.1.6/lib/aliyun/oss/protocol.rb:522:in `put_object'  
/home/www/.rvm/gems/ruby-2.2.1/gems/aliyun-sdk-0.1.6/lib/aliyun/oss/bucket.rb:203:in `put_object'
```

**Comment by rockuw** [comment]
你把log级别设成INFO试试，这个inspect只有在log的时候用。我回去看下原因。

**Comment by charlescui** [comment]
`/home/www/.rvm/gems/ruby-2.2.1/gems/aliyun-sdk-0.1.6/lib/aliyun/oss/http.rb:228`

```
#logger.debug("Send HTTP request, verb: #{verb}, resources: " \
              #"#{resources}, http options: #{http_options}")
```

你去看下这里，如果是图片，会在这里报错。
