### ISSUE TITLE
Running example error

### ISSUE THREAD

**Issue by oksep** [aliyun/aliyun-oss-ruby-sdk#38]
cannot load crcx

```
/Users/septenary/Documents/pro_ruby/aliyun-oss-ruby-sdk/lib/aliyun/oss.rb:17:in `require_relative': cannot load such file -- /Users/septenary/Documents/pro_ruby/aliyun-oss-ruby-sdk/lib/aliyun/crcx (LoadError)
	from /Users/septenary/Documents/pro_ruby/aliyun-oss-ruby-sdk/lib/aliyun/oss.rb:17:in `<top (required)>'
	from /Users/septenary/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/septenary/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from examples/aliyun/oss/bucket.rb:5:in `<main>
```

**Comment by rocLv** [comment]
@Ryfthink Try `bundle update` to update rake version.

**Comment by luluhongxu** [comment]
@Ryfthink ：  Please show me your developing enviroment ：Linux version,  Ruby verison ,  Rake version , Aliyun-sdk version . 
I have installed aliyun-sdk in Ubuntu 16.04 for several times, Once you install aliyun-sdk successfully, then you certainly get the crcx.so in the path /var/lib/gems/2.3.0/gems/aliyun-sdk-0.6.0/lib/aliyun/crcx.so,  never failed  .

**Comment by luluhongxu** [comment]
@Ryfthink ： I suggest you install zlib1g-dev again with command below, and then try it again. 
```
sudo apt install  zlib1g-dev
```

**Comment by AriaLyy** [comment]
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
