### ISSUE TITLE
RestClient 被赋予 logger 之后和 StreamWriter 不兼容

### ISSUE THREAD

**Issue by snow** [aliyun/aliyun-oss-ruby-sdk#65]
### sdk 版本
https://github.com/aliyun/aliyun-oss-ruby-sdk/commit/29b8807c4488720eec77b1a2af0bd50aeed76ac5

### 重现步骤
(in shell)
```shell
echo 'hello' > test.txt
```
(in ruby console) 
```ruby
logger = Logger.new(STDOUT)
logger.level = Logger::WARN
RestClient.log = logger
bucket.put_object('test/test.txt', file: '/path/to/text.txt') # given bucket is a Aliyun::OSS::Bucket
# Exception: NoMethodError: undefined method `>' for nil:NilClass
# --
# 0: /path/to/rest-client-2.0.2/lib/restclient/payload.rb:84:in `short_inspect'
# 1: /path/to/rest-client-2.0.2/lib/restclient/request.rb:534:in `log_request'
# 2: /path/to/rest-client-2.0.2/lib/restclient/request.rb:713:in `transmit'
# 3: /path/to/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
# 4: /path/to/aliyun-oss-ruby-sdk-31e051628fdf/lib/aliyun/oss/http.rb:269:in `do_request'
# 5: /path/to/aliyun-oss-ruby-sdk-31e051628fdf/lib/aliyun/oss/http.rb:189:in `put'
# 6: /path/to/aliyun-oss-ruby-sdk-31e051628fdf/lib/aliyun/oss/protocol.rb:539:in `put_object'
# 7: /path/to/aliyun-oss-ruby-sdk-31e051628fdf/lib/aliyun/oss/bucket.rb:218:in `put_object'
```

### 原因
oss sdk 把 Aliyun::OSS::HTTP::StreamWriter 当作 Stream 传给了 RestClient, RestClient::Payload.generate 判断为 RestClient::Payload::Streamed, 随后如果被赋予了 logger, 就会访问 StreamWriter 的 `size`, `seek` 方法。

### 解决
目前 patch 一下 StreamWriter 就可以正常工作
```ruby
module Aliyun
  module OSS
    class HTTP
      class StreamWriter

        def size
          @buffer.size
        end

        def seek(*); end

      end
    end
  end
end
```

但是我不确定让 StreamWriter acts even more like a stream 是不是一个好的方向。既然它只是个用作 buffer 的 String 加上 crc 之类的辅助属性, 也许用 String 的子类也是一个可能的出路？我没有往这个方向深入思考，所以只把意见提出来，希望能抛砖引玉。

**Comment by rockuw** [comment]
多谢反馈！当初是希望在上传文件的时候，能够让上传的数据generate on the fly，所以才有了StreamWriter/Fiber.yield等等，并且只提供了这种方式，更常用的上传一个文件/一段buffer都是基于这个来实现的。

我应该反省一下，这样做会有一些问题(例如没法指定Content-MD5)，SDK应该target更常用的场景。希望在后续版本中能够改进。

**Comment by tianlu1677** [comment]
遇到同样的问题.

在使用
```
bucket.put_object(xkey, file: '/tmp/a.png')
```
会报错
```
Put file failed: undefined method `seek' for @buffer: ""...0 bytes:Aliyun::OSS::HTTP::StreamWriter 
```
打了patch就好了

**Comment by ghost** [comment]
打了patch 又出来了Aliyun::OSS::CrcInconsistentError

**Comment by ghost** [comment]
test code 

```
    RestClient.log = STDOUT
    # test code
    OSS.default_bucket.put_object("csv/test11", file: administrator_params[:logo].path)
```

request 

```
{"_method"=>"patch",
 "authenticity_token"=>"7W74Hv4JyeMB+6UBpq9F8nmyLtrI81wseM2DGsmHOV5wOloVp7G+8DP/0jOPuB2rJ9z0L7XtnD95KixXAMLWgA==",
 "administrator"=>
  {"name"=>"123",
   "password"=>"[FILTERED]",
   "phone"=>"11",
   "logo"=>
    #<ActionDispatch::Http::UploadedFile:0x00007ffa0a418578
     @content_type="text/csv",
     @headers=
      "Content-Disposition: form-data; name=\"administrator[logo]\"; filename=\"\xE6\x89\xB9\xE9\x87\x8F\xE5\x8F\x91\xE8\xB4\xA7\xE6\xA8\xA1\xE6\x9D\xBF.csv\"\r\n" + "Content-Type: text/csv\r\n",
     @original_filename="批量发货模板.csv",
     @tempfile=#<File:/var/folders/q_/bmw7x38529lg5zjm9wb7v0cr0000gn/T/RackMultipart20200311-66924-17r4q1b.csv>>,
   "role_ids"=>[""],
   "types"=>"supplier_admin"},
 "commit"=>"更新管理员",
 "id"=>"36"}
```
error 
```
The crc of put between client and oss is not inconsistent.
```

![image](https://user-images.githubusercontent.com/12042737/76401990-bc756380-63bd-11ea-8cbb-43a8359e4dec.png)

console.log 

```
Started PATCH "/admin/administrators/36" for ::1 at 2020-03-11 17:26:55 +0800
Processing by Admin::AdministratorsController#update as HTML
  Parameters: {"authenticity_token"=>"7W74Hv4JyeMB+6UBpq9F8nmyLtrI81wseM2DGsmHOV5wOloVp7G+8DP/0jOPuB2rJ9z0L7XtnD95KixXAMLWgA==", "administrator"=>{"name"=>"123", "password"=>"[FILTERED]", "phone"=>"11", "logo"=>#<ActionDispatch::Http::UploadedFile:0x00007ffa0a418578 @tempfile=#<Tempfile:/var/folders/q_/bmw7x38529lg5zjm9wb7v0cr0000gn/T/RackMultipart20200311-66924-17r4q1b.csv>, @original_filename="批量发货模板.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"administrator[logo]\"; filename=\"\xE6\x89\xB9\xE9\x87\x8F\xE5\x8F\x91\xE8\xB4\xA7\xE6\xA8\xA1\xE6\x9D\xBF.csv\"\r\nContent-Type: text/csv\r\n">, "role_ids"=>[""], "types"=>"supplier_admin"}, "commit"=>"更新管理员", "id"=>"36"}
  Administrator Load (1.2ms)  SELECT `administrators`.* FROM `administrators` WHERE `administrators`.`id` = 1 LIMIT 1
  ↳ app/controllers/admin/base_controller.rb:25:in `current_admin'
  Administrator Load (15.9ms)  SELECT `administrators`.* FROM `administrators` WHERE `administrators`.`id` = 36 LIMIT 1
  ↳ app/controllers/admin/administrators_controller.rb:57:in `set_administrator'
RestClient.put "https://zhi-oss-staging.mmcb.store/csv%2Ftest11", "\xE8\xAE\xA2\xE5\x8D\x95ID,\xE7\x89\xA9\xE6\xB5\x81\xE5\x85\xAC\xE5\x8F\xB8,\xE7\x89\xA9\xE6\xB5\x81\xE5\x8D\x95\xE5\x8F\xB7\r\n307a20200213131731200617,\xE9\xA1\xBA\xE4\xB8\xB0\xE9\x80\x9F\xE8\xBF\x90,123000\r\n280o20200210161350417462,\xE6\x97\xA0\xE9\x9C\x80\xE7\x89\xA9\xE6\xB5\x81,\r\n281o20200210162413252366,\xE6\x97\xA0\xE9\x9C\x80\xE7\x89\xA9\xE6\xB5\x81,\r\n282o20200210162413655236,\xE6\x97\xA0\xE9\x9C\x80\xE7\x89\xA9\xE6\xB5\x81,\r\n", "Accept"=>"*/*", "User-Agent"=>"rest-client/2.1.0 (darwin19.0.0 x86_64) ruby/2.6.5p114", "accept-encoding"=>"identity", "authorization"=>"OSS LTAIa9UlV8pjCiOa:YsI9jBSd5w0yirbLbqOav/Ac1l8=", "content-length"=>"202", "content-type"=>"text/csv", "date"=>"Wed, 11 Mar 2020 09:26:56 GMT", "transfer-encoding"=>"chunked", "user-agent"=>"aliyun-sdk-ruby/0.7.1 ruby-2.6.5/x86_64-darwin19"
# => 200 OK |  0 bytes, 0.22s
Completed 500 Internal Server Error in 553ms (ActiveRecord: 17.0ms | Allocations: 4446497)


Aliyun::OSS::CrcInconsistentError excluded from capture: Not configured to send/capture in environment 'development'

Aliyun::OSS::CrcInconsistentError (The crc of put between client and oss is not inconsistent.):

```

**Comment by ghost** [comment]
upload_crc_enable: false
先手动关了
